# Generated by Django 4.1.1 on 2022-10-04 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_post_category_alter_post_released_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='released_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 4, 12, 42, 38, 200441)),
        ),
    ]
